#import "Object"
#import "C_loader"
#import "C_aggregator"
#import "C_exporter"

object C_engine implements Object {
    fields {}

    init {}

    (char*) self |> "load file" |> (char*): filename |>
        return (C_loader "new" filename) "load";

    (char*) self |> "aggregate data" |>
        return (C_aggregator "new") "aggregate";

    (void*) self |> "export file" |> (char*): filename, (char*): type |>
        return (C_exporter "new" filename, type) "export";

    defer {}
}
