#import "Object"

object C_exporter implements Object((char*): filename, (char*): type) {
    fields {
        char *filename;
        char *type;
    }

    init {
        self->filename = filename;
        self->type = type;
    }

    (char*) self |> "get filename" |> return self->filename;
    (char*) self |> "get type" |> return self->type;

    (void*) self |> "export" |> /* exec consturctor */ return self;

    defer {}
}
