#import "Object"

#import "M_file_handler"

object C_loader implements Object((char*): filename) {
    fields {
        char *filename;
        void *handler;
    }

    init {
        self->filename = filename;
        self->handler = M_file_handler "new" self->filename;
    }

    // (void) self |> "load" |> printf("Loading file: `%s`\n", self->filename);
    (char*) self |> "load" |> return "l";

    defer {}
}
